### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by llvilanova** [aclements/libelfin#11]
I'm working on packaging libelfin (as a dependency for coz), and I'd appreciate it if you can make a new release. The latest one (0.1) has no "install" target and still does not use "-fPIC", and I'd prefer not to package a snapshot.

**Comment by aclements** [comment]
I'd be happy to. I'll make a release once the shared library addition is in.

**Comment by llvilanova** [comment]
Great, thx!

**Comment by aclements** [comment]
Just rolled v0.2.
