### ISSUE TITLE
coz: DW_FORM_sec_offset not expected for attribute (DW_AT)0x2137 / 0x2119

### ISSUE THREAD

**Issue by timo** [aclements/libelfin#39]
coz, the causal profiler, uses libelfin to parse dwarf data, and multiple users have stumbled upon the error message in the title (https://github.com/plasma-umass/coz/issues/107)

**Comment by jesperpedersen** [comment]
0x2119 and 0x2137 are GNU extensions to the DWARF format

https://github.com/gcc-mirror/gcc/blob/master/include/dwarf2.def#L441
https://github.com/gcc-mirror/gcc/blob/master/include/dwarf2.def#L454
