### ISSUE TITLE
Building examples doesn't work 

### ISSUE THREAD

**Issue by abenkhadra** [aclements/libelfin#4]
I'm trying to build the examples and started with `dump-lines.cc` following the documentation. However, build fails to due missing type definitions and symbols. For instance,  type definitions for  `section_offset`, `section_length` and `DW_AT` are missing. I couldn't find the missing definitions in the sources. Therefore, I'm assuming that you depend on some external library. Can you please provide the dependencies of `libelfin`.

**Comment by zeldovich** [comment]
All of the three names you mention are defined in `dwarf/data.hh`, which gets included by `dwarf/dwarf++.hh`, which in turn is included by `examples/dump-lines.cc`.

**Comment by abenkhadra** [comment]
I moved all header files in `elf` and `dwarf` directories to a single include directory in my project and since there are two `data.hh` files, one of them has got accidentally overwritten. I went back to the original sources and found the definitions in `dwarf/data.hh`. 

Many thanks.
